// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  按状态筛选工单列表，按 priority 升序、updated_at 降序排列；`query` 为空时不做文本筛选。 */
	listWorkOrders: (statuses: string[], includeCompleted: boolean, query: string) => __TAURI_INVOKE<WorkOrder[]>("list_work_orders", { statuses, includeCompleted, query }),
	/**  按 id 获取单条工单，不存在时返回 `NOT_FOUND`。 */
	getWorkOrder: (id: number) => __TAURI_INVOKE<WorkOrder>("get_work_order", { id }),
	/**  创建工单；title 必填，priority 自动递增。 */
	createWorkOrder: (input: WorkOrderInput) => __TAURI_INVOKE<WorkOrder>("create_work_order", { input }),
	/**  更新工单；若进入或变更「待回复」状态，会自动追加进度日志。 */
	updateWorkOrder: (id: number, input: WorkOrderInput) => __TAURI_INVOKE<WorkOrder>("update_work_order", { id, input }),
	/**  删除工单及其全部进度日志。 */
	deleteWorkOrder: (id: number) => __TAURI_INVOKE<null>("delete_work_order", { id }),
	/**  按给定 id 顺序批量更新 priority（用于拖拽排序）。 */
	updatePriorities: (orderedIds: number[]) => __TAURI_INVOKE<null>("update_priorities", { orderedIds }),
	/**  判断工单是否逾期（有 due_date、未完成且早于当前时间）。 */
	isWorkOrderOverdue: (workOrder: WorkOrder) => __TAURI_INVOKE<boolean>("is_work_order_overdue", { workOrder }),
	/**  列出指定工单下的全部进度日志，按 created_at 降序。 */
	listProgressLogs: (workOrderId: number) => __TAURI_INVOKE<ProgressLog[]>("list_progress_logs", { workOrderId }),
	/**  为工单添加进度日志，content 不能为空。 */
	addProgressLog: (workOrderId: number, content: string) => __TAURI_INVOKE<ProgressLog>("add_progress_log", { workOrderId, content }),
	/**  更新进度日志内容；log 必须属于指定工单。 */
	updateProgressLog: (logId: number, workOrderId: number, content: string) => __TAURI_INVOKE<ProgressLog>("update_progress_log", { logId, workOrderId, content }),
	/**  删除进度日志；log 必须属于指定工单。 */
	deleteProgressLog: (logId: number, workOrderId: number) => __TAURI_INVOKE<null>("delete_progress_log", { logId, workOrderId }),
	getSettings: () => __TAURI_INVOKE<SettingsInfo>("get_settings"),
	pickDataDir: () => __TAURI_INVOKE<string | null>("pick_data_dir"),
	changeDataDir: (newPath: string) => __TAURI_INVOKE<ChangeDataDirResult>("change_data_dir", { newPath }),
	restartApp: () => __TAURI_INVOKE<null>("restart_app"),
};

/* Types */
export type ChangeDataDirResult = {
	success: boolean,
	restartRequired: boolean,
	newDataDir: string,
};

/**  工单下的单条进度记录。 */
export type ProgressLog = {
	id: number | null,
	workOrderId: number,
	content: string,
	createdAt: string,
};

export type SettingsInfo = {
	dataDir: string,
	settingsPath: string,
	envOverride: boolean,
	defaultDataDir: string,
};

/**  工单完整记录（含 id、priority 与时间戳）。 */
export type WorkOrder = {
	id: number | null,
	title: string,
	description: string | null,
	status: WorkOrderStatus,
	priority: number,
	waitingFor: string | null,
	waitingReason: string | null,
	dueDate: string | null,
	createdAt: string,
	updatedAt: string,
};

/**  创建或更新工单时的输入（不含 priority 与时间戳，由 Service 层填充）。 */
export type WorkOrderInput = {
	title: string,
	description: string | null,
	status: WorkOrderStatus,
	waitingFor: string | null,
	waitingReason: string | null,
	dueDate: string | null,
};

/**  工单生命周期状态，与数据库 `VARCHAR` 及前端 `WorkOrderStatus` 对齐。 */
export type WorkOrderStatus = "NOT_STARTED" | "IN_PROGRESS" | "WAITING_REPLY" | "COMPLETED";

