// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  按状态筛选工单列表，按 priority 升序、updated_at 降序排列；`query` 为空时不做文本筛选。 */
	listWorkOrders: (statuses: string[], query: string) => __TAURI_INVOKE<WorkOrder[]>("list_work_orders", { statuses, query }),
	/**  按 id 获取单条工单，不存在时返回 `NOT_FOUND`。 */
	getWorkOrder: (id: number) => __TAURI_INVOKE<WorkOrder>("get_work_order", { id }),
	/**  创建工单；title 必填，priority 自动递增。 */
	createWorkOrder: (input: WorkOrderInput) => __TAURI_INVOKE<WorkOrder>("create_work_order", { input }),
	/**  更新工单。 */
	updateWorkOrder: (id: number, input: WorkOrderInput) => __TAURI_INVOKE<WorkOrder>("update_work_order", { id, input }),
	/**  删除工单及其全部进度日志。 */
	deleteWorkOrder: (id: number) => __TAURI_INVOKE<null>("delete_work_order", { id }),
	/**  按给定 id 顺序批量更新 priority（用于拖拽排序）。 */
	updatePriorities: (orderedIds: number[]) => __TAURI_INVOKE<null>("update_priorities", { orderedIds }),
	/**  判断工单是否逾期（有 due_date 且早于当前时间）。 */
	isWorkOrderOverdue: (workOrder: WorkOrder) => __TAURI_INVOKE<boolean>("is_work_order_overdue", { workOrder }),
	getStatusConfig: () => __TAURI_INVOKE<StatusConfig>("get_status_config"),
	saveStatusConfig: (config: StatusConfig) => __TAURI_INVOKE<null>("save_status_config", { config }),
	/**  列出指定工单下的全部进度日志，按 created_at 降序。 */
	listProgressLogs: (workOrderId: number) => __TAURI_INVOKE<ProgressLog[]>("list_progress_logs", { workOrderId }),
	/**  为工单添加进度日志，title 不能为空。 */
	addProgressLog: (workOrderId: number, input: ProgressLogInput) => __TAURI_INVOKE<ProgressLog>("add_progress_log", { workOrderId, input }),
	/**  更新进度日志；log 必须属于指定工单。 */
	updateProgressLog: (logId: number, workOrderId: number, input: ProgressLogInput) => __TAURI_INVOKE<ProgressLog>("update_progress_log", { logId, workOrderId, input }),
	/**  删除进度日志；log 必须属于指定工单。 */
	deleteProgressLog: (logId: number, workOrderId: number) => __TAURI_INVOKE<null>("delete_progress_log", { logId, workOrderId }),
	getSettings: () => __TAURI_INVOKE<SettingsInfo>("get_settings"),
	pickDataDir: () => __TAURI_INVOKE<string | null>("pick_data_dir"),
	changeDataDir: (newPath: string) => __TAURI_INVOKE<ChangeDataDirResult>("change_data_dir", { newPath }),
	pickBackupSavePath: () => __TAURI_INVOKE<string | null>("pick_backup_save_path"),
	pickBackupFile: () => __TAURI_INVOKE<string | null>("pick_backup_file"),
	exportBackup: (savePath: string) => __TAURI_INVOKE<ExportBackupResult>("export_backup", { savePath }),
	importBackup: (zipPath: string) => __TAURI_INVOKE<ImportBackupResult>("import_backup", { zipPath }),
	restartApp: () => __TAURI_INVOKE<null>("restart_app"),
	listAttachments: (ownerType: OwnerType, ownerId: number) => __TAURI_INVOKE<Attachment[]>("list_attachments", { ownerType, ownerId }),
	addAttachmentFromFile: (ownerType: OwnerType, ownerId: number, sourcePath: string) => __TAURI_INVOKE<Attachment>("add_attachment_from_file", { ownerType, ownerId, sourcePath }),
	addAttachmentFromBytes: (ownerType: OwnerType, ownerId: number, fileName: string, mimeType: string, data: number[]) => __TAURI_INVOKE<Attachment>("add_attachment_from_bytes", { ownerType, ownerId, fileName, mimeType, data }),
	deleteAttachment: (id: number) => __TAURI_INVOKE<null>("delete_attachment", { id }),
	/**  打开图片文件选择器，返回选中路径（未选则 None）。 */
	pickAttachmentFile: () => __TAURI_INVOKE<string | null>("pick_attachment_file"),
};

/* Types */
export type Attachment = {
	id: number | null,
	ownerType: OwnerType,
	ownerId: number,
	fileName: string,
	originalName: string | null,
	mimeType: string,
	fileSize: number,
	createdAt: string,
	/**  完整磁盘路径，查询时由 service 填充，不存 DB。 */
	filePath: string,
};

export type ChangeDataDirResult = {
	success: boolean,
	restartRequired: boolean,
	newDataDir: string,
};

export type ExportBackupResult = {
	success: boolean,
	filePath: string,
};

export type ImportBackupResult = {
	success: boolean,
	restartRequired: boolean,
};

export type OwnerType = "work_order" | "progress_log";

/**  工单下的单条进度记录。 */
export type ProgressLog = {
	id: number | null,
	workOrderId: number,
	title: string,
	content: string | null,
	status: string,
	createdAt: string,
};

/**  创建或更新进度记录时的输入。 */
export type ProgressLogInput = {
	title: string,
	content: string | null,
	status: string,
};

export type SettingsInfo = {
	dataDir: string,
	settingsPath: string,
	envOverride: boolean,
	defaultDataDir: string,
};

/**  数据目录中的 `status_config.json` 根结构。 */
export type StatusConfig = {
	version: number,
	statuses: StatusDefinition[],
};

/**  单个代办状态定义。 */
export type StatusDefinition = {
	id: string,
	label: string,
	order: number,
	fields: StatusField[],
};

/**  某状态下的一条可填字段。 */
export type StatusField = {
	key: string,
	label: string,
	type: StatusFieldType,
	required: boolean,
};

/**  状态字段类型。 */
export type StatusFieldType = "text" | "textarea" | "date";

/**  工单完整记录（含 id、priority 与时间戳）。 */
export type WorkOrder = {
	id: number | null,
	title: string,
	description: string | null,
	status: string,
	priority: number,
	extraFields: { [key in string]: string } | null,
	dueDate: string | null,
	createdAt: string,
	updatedAt: string,
};

/**  创建或更新工单时的输入（不含 priority 与时间戳，由 Service 层填充）。 */
export type WorkOrderInput = {
	title: string,
	description: string | null,
	status: string,
	extraFields: { [key in string]: string } | null,
	dueDate: string | null,
};

